### ISSUE TITLE
FR: Support remote notebooks

### ISSUE THREAD

**Issue by sjsrey** [pysal/geopyter#38]
I don't think we ever got around to implementing the use of remote notebooks, which would obviously be a rather useful feature since it saves the user even having to download/clone notebooks from GitHub! Behind the scenes we can always download to a local tmp directory in order to pass the data to our processor, but the user doesn't need to know that.

So something like:
@include {
     'nb' = 'https://github.com/kingsgeocomp/code-camp/blob/master/notebook-02.ipynb'
}

The only downside I can see to this is that if you want a particular version you can't use a branch without changing the URL... but I *think* you can still use tags that are on the master right? So we could still (I believe) write:

@include {
     'nb' = 'https://github.com/kingsgeocomp/code-camp/blob/master/notebook-02.ipynb',
     'tag' = 'v1_2', # Note, doesn't exist, just for illustrative purposes
     'select' = 'h1.Understanding Lists'
}

**Comment by sjsrey** [comment]
I think we can handle this as we can test for the scheme in the opener and dispatch accordingly.
On a related note, urllib has undergone major refactoring between python2 and python3. We started with python2 for this project but I think we might want to revisit that decision as a lot content is now python3 only. We probably don't want to have two versions of gp, or one version that can support 2 and 3 (having scars that are still not healed from the pysal 2 to 3 transition).

**Comment by jreades** [comment]
Yep, fine with dropping support for python 2!

--
m: 07976987392
e: jon@reades.com
s: jreades

**Comment by sjsrey** [comment]
Cool. I'll work on refactoring to 3 only and handling the remote v. local reads.

**Comment by jreades** [comment]
Resolved. Though I think it still outputs a message the remote reads aren't supported.
